// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7TgNrWQj5NP1iabd7btsp3
// Component: o1ls_a0IAWOOXD
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_normangershman_com.module.css"; // plasmic-import: 7TgNrWQj5NP1iabd7btsp3/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: o1ls_a0IAWOOXD/css
import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: IB0J-UmDlibecY/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: oj5FNsn2EUpqtw/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: R8tUcBx7u61-RR/icon

export const PlasmicRating__VariantProps = new Array("rating");

export const PlasmicRating__ArgProps = new Array();

function PlasmicRating__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__x0Fcq, {
          [sty.svgrating_five__x0FcqNDl1L]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__x0Fcql9Mwp]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__x0FcqKwnJv]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_half__x0FcqHKuQ3]: hasVariant(
            variants,
            "rating",
            "half"
          ),

          [sty.svgrating_oneHalf__x0FcqVlP9D]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_one__x0Fcqshtu7]: hasVariant(
            variants,
            "rating",
            "one"
          ),

          [sty.svgrating_threeHalf__x0Fcq41YTv]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__x0Fcqyss0J]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__x0Fcqb06Po]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__x0FcqdnNki]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__rzj5T, {
          [sty.svgrating_five__rzj5TNDl1L]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__rzj5Tl9Mwp]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__rzj5TKwnJv]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_oneHalf__rzj5TVlP9D]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_threeHalf__rzj5T41YTv]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__rzj5Tyss0J]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__rzj5Tb06Po]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__rzj5TdnNki]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__rG1L, {
          [sty.svgrating_five__rG1LNDl1L]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__rG1Ll9Mwp]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__rG1LKwnJv]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__rG1L41YTv]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__rG1Lyss0J]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__rG1Lb06Po]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__kLrk, {
          [sty.svgrating_five__kLrknDl1L]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__kLrKl9Mwp]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__kLrkkwnJv]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__kLrk41YTv]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__wgVv, {
          [sty.svgrating_five__wgVvNDl1L]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__wgVvl9Mwp]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
