// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import Lightroom from 'react-lightbox-gallery'
import { PlasmicImageGallery } from "./plasmic/normangershman_com/PlasmicImageGallery";

function ImageGallery_(props, ref) {

  var images = [
    {
      src: "https://images.unsplash.com/photo-1577279549270-b9e297533cdd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80",
      desc: 'Person wearing shoes',
      sub: 'Gift Habeshaw'
    },
    {
      src: "https://images.unsplash.com/photo-1577277625082-36df4915ebeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
      desc: 'Blonde woman wearing sunglasses smiling at the camera ',
      sub: 'Dmitriy Frantsev'
    }
  ]
  var settings = {
    columnCount:{
      default:5,
      mobile:3,
      tab:4
    },
    mode: 'dark'
  }

  // Use PlasmicImageGallery to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicImageGallery are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ImageGalleryProps here, but feel free
  // to do whatever works for you.
  //return <PlasmicImageGallery root={{ ref }} {...props} />;
  return <PlasmicImageGallery>
      <div>
        <Lightroom images={images} settings={settings} />
      </div>
  </PlasmicImageGallery>
}

const ImageGallery = React.forwardRef(ImageGallery_);

export default ImageGallery;
